
name: mad_real_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.3.0
  map_launcher: ^3.3.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  provider: ^6.1.2
  firebase_ui_auth: ^1.14.0
  lottie: ^3.1.2
  speech_to_text: ^6.1.1
  firebase_messaging: ^14.3.0
  flame: ^1.10.0
  flame_audio: ^2.1.2
  #cupertino_icons: ^1.0.2
  flutter_naver_map: ^1.2.2+flutter3.22



dev_dependencies:

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/angelic_lung.png
    - assets/my_lung.json
    - assets/running_man.json
    - assets/reading_woman.json
    - assets/images/
    - assets/audio/

  fonts:
    - family: Game     
      fonts:
        - asset: assets/fonts/Game.ttf
