// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0r7M-wA-uiZDc1PRsgwMsRAibkMAutw0',
    appId: '1:1052926683011:web:b7a5a8a1cfaf9b6d27f8b6',
    messagingSenderId: '1052926683011',
    projectId: 'mad-team-project',
    authDomain: 'mad-team-project.firebaseapp.com',
    storageBucket: 'mad-team-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe2zqCLPU8jGfl_usq4O6VVBW6U_mimIk',
    appId: '1:1052926683011:android:3985aab18ec0098b27f8b6',
    messagingSenderId: '1052926683011',
    projectId: 'mad-team-project',
    storageBucket: 'mad-team-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTjozQa6Wn1NzlWErEUCryiNq3Ws1etQ',
    appId: '1:1052926683011:ios:31b698c2d35a663d27f8b6',
    messagingSenderId: '1052926683011',
    projectId: 'mad-team-project',
    storageBucket: 'mad-team-project.appspot.com',
    iosClientId: '1052926683011-8355681a7fg2akgch62qomii45sv9plf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flappyBirdGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhTjozQa6Wn1NzlWErEUCryiNq3Ws1etQ',
    appId: '1:1052926683011:ios:31b698c2d35a663d27f8b6',
    messagingSenderId: '1052926683011',
    projectId: 'mad-team-project',
    storageBucket: 'mad-team-project.appspot.com',
    iosClientId: '1052926683011-8355681a7fg2akgch62qomii45sv9plf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flappyBirdGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0r7M-wA-uiZDc1PRsgwMsRAibkMAutw0',
    appId: '1:1052926683011:web:705de55f8013032827f8b6',
    messagingSenderId: '1052926683011',
    projectId: 'mad-team-project',
    authDomain: 'mad-team-project.firebaseapp.com',
    storageBucket: 'mad-team-project.appspot.com',
  );
}
